organizer/urls.py
from django.urls import path
from events import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('events/new', views.new_list, name='new_list'),
    path('events/<str:list_id>/', views.view_list, name='view_list'),
    path('events/<str:list_id>/add_item', views.add_item, name='add_item'),
]

events/models.py
from django.db import models


class List(models.Model):
    'Список'

    pass


class Item(models.Model):
    'Элемент списка'

    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

events/views.py
from django.shortcuts import redirect, render
from events.models import Item, List


def home_page(request):
    return render(request, 'home.html')

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    return render(request, 'list.html', {'list': list_})

def new_list(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect(f'/events/{list_.id}/')

def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect(f'/events/{list_.id}/')

events/templates/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Органайзер</title>
        <link href="/static/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/base.css" rel="stylesheet">
    </head>

    <body>
        <div class="container">

            <div class="row">
                <div class="col-md-6 col-md-offset-3 jumbotron">
                    <div class="text-center">

                        <h1>{% block header_text %}{% endblock %}</h1>

                        <form method="POST" action="{% block form_action %}{% endblock %}">

                            <input name="item_text" id="id_new_item"
                                class="form-control input-lg" 
                                placeholder="Новое событие" />

                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    {% block table %}
                    {% endblock %}
                </div>
            </div>

        </div>

    </body>

</html>

events/templates/home.html
{% extends "base.html" %}

{% block header_text %}Начать новый список{% endblock header_text %}

{% block form_action %}/events/new{% endblock form_action %}

events/templates/list.html
{% extends "base.html" %}

{% block header_text %}Список событий{% endblock header_text %}

{% block form_action %}/events/{{ list.id }}/add_item{% endblock form_action %}

{% block table %} 

    <table id="id_events_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>

{% endblock table %} 